### ISSUE TITLE
你好，可以分享一下LCSTS2.0原始数据集吗？

### ISSUE THREAD

**Issue by nlpchen** [OrangeInSouth/LSSD#1]
你好，可以分享一下LCSTS2.0原始数据集吗？我按官方的填写了申请，一直没有收到他们的回信，CSDN的链接也失效的，多谢。[nlp_chen@163.com](mailto:nlp_chen@163.com)

**Comment by OrangeInSouth** [comment]
你好，我这也没有LCSTS2.0数据集。

另外，这个repository主要用于讨论"[Unifying the Convergences in Multilingual Neural Machine Translation](https://arxiv.org/abs/2205.01620)."相关的内容
